name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - name: label when approved
        uses: abinoda/label-when-approved-action@1.0.5
        env:
          APPROVALS: 1
          GITHUB_TOKEN: ${{ sevrets.GITHUB_TOKEN }}
          ADD_LABEL: "APPROVED"
          REMOVE_LABEL:"Awaiting%20review"
